### ISSUE TITLE
Print SCP - P-Data-TF PDU: System.NullReferenceException

### ISSUE THREAD

**Issue by silvalooky** [fo-dicom/fo-dicom-samples#13]
I'm using PrintSCP latest released version (2017.01) , and I've this exception : 
`Exception processing P-Data-TF PDU: System.NullReferenceException: Object reference not set to an instance of an object.`
The exception is caused when the images are received with AGFA system, and after the error the same images will be repeat again and again with the same exception' scenario 

this's the whole log for this exception :
```
AGFA <- Association request:
Calling AE Title:       AGFA
Called AE Title:        PRINTSCP
Remote host:            192.168.0.201
Remote port:            1405
Implementation Class:   Implementation Class UID [1.3.51.0.1.3]
Implementation Version: DPM1.00
Maximum PDU Length:     65542
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  5
  Presentation Context:  1 [Proposed]
       Abstract Syntax:  Basic Grayscale Print Management Meta SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  3 [Proposed]
       Abstract Syntax:  Verification SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  5 [Proposed]
       Abstract Syntax:  Print Job SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  7 [Proposed]
       Abstract Syntax:  Basic Annotation Box SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  9 [Proposed]
       Abstract Syntax:  Print Queue Management SOP Class (Retired)
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
Received association request from AE: AGFA with IP: 127.0.0.1
Requested abstract syntax Basic Annotation Box SOP Class [1.2.840.10008.5.1.1.15] from AGFA not supported
Requested abstract syntax Print Queue Management SOP Class (Retired) [1.2.840.10008.5.1.1.26] from AGFA not supported
Accepted association request from AGFA
AGFA -> Association accept:
Calling AE Title:       AGFA
Called AE Title:        PRINTSCP
Remote host:            192.168.0.201
Remote port:            1405
Implementation Class:   Implementation Class UID [1.3.51.0.1.3]
Implementation Version: DPM1.00
Maximum PDU Length:     65542
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  5
  Presentation Context:  1 [Accept]
       Abstract Syntax:  Basic Grayscale Print Management Meta SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  3 [Accept]
       Abstract Syntax:  Verification SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  5 [Accept]
       Abstract Syntax:  Print Job SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  7 [RejectAbstractSyntaxNotSupported]
       Abstract Syntax:  Basic Annotation Box SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  9 [RejectAbstractSyntaxNotSupported]
       Abstract Syntax:  Print Queue Management SOP Class (Retired)
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
AGFA <- N-Create request [1]
Create new film session 2.25.85941031861403720812711862200051664058
-------------------------------------------------------------------------------------------------
Exception processing P-Data-TF PDU: System.NullReferenceException: Object reference not set to an instance of an object.
   at Dicom.DicomUniqueIdentifier.<>c.<.ctor>b__1_0(DicomUID x) in C:\fo-dicom\DICOM\DicomElement.cs:line 1690
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Dicom.DicomUniqueIdentifier..ctor(DicomTag tag, DicomUID[] values) in C:\fo-dicom\DICOM\DicomElement.cs:line 1690
   at Dicom.DicomDataset.DoAdd[T](DicomVR vr, DicomTag tag, IList`1 values, Boolean allowUpdate) in C:\fo-dicom\DICOM\DicomDataset.cs:line 798
   at Dicom.DicomDataset.DoAdd[T](DicomTag tag, IList`1 values, Boolean allowUpdate) in C:\fo-dicom\DICOM\DicomDataset.cs:line 552
   at Dicom.Network.DicomNCreateResponse.set_SOPInstanceUID(DicomUID value) in C:\fo-dicom\DICOM\Network\DicomNCreateResponse.cs:line 48
   at Dicom.Printing.PrintService.CreateFilmSession(DicomNCreateRequest request) in E:\fo-dicom-samples\Desktop\Print SCP\PrintService.cs:line 215
   at Dicom.Printing.PrintService.OnNCreateRequest(DicomNCreateRequest request) in E:\fo-dicom-samples\Desktop\Print SCP\PrintService.cs:line 183
   at Dicom.Network.DicomService.PerformDimse(DicomMessage dimse) in C:\fo-dicom\DICOM\Network\DicomService.cs:line 798
   at Dicom.Network.DicomService.<ProcessPDataTFAsync>d__55.MoveNext() in C:\fo-dicom\DICOM\Network\DicomService.cs:line 679
-------------------------------------------------------------------------------------------------
```

**Comment by gofal** [comment]
This issue should be solved. There was an update in April 2017. Please fetch the latest sources and try again.

**Comment by gofal** [comment]
See #4
