### ISSUE TITLE
 printcp Socket error while reading PDU: ConnectionReset [10054]   && [ERROR] Exception creating PDV: FellowOakDicom.Network.DicomNetworkException: An IO exception occurred while sending a PDU ---> System.IO.IOException

### ISSUE THREAD

**Issue by jm001a** [fo-dicom/fo-dicom-samples#83]
[INFO] LINUX_DCP <- Association request:
Calling AE Title:       LINUX_DCP
Called AE Title:        DRYPIX
Remote host:            192.168.20.11
Remote port:            35954
Implementation Class:   Implementation Class UID [1.2.840.113619.6.81]
Implementation Version: fo-dicom 5.0.3
Maximum PDU Length:     16384
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  5
  Presentation Context:  1 [Proposed]
       Abstract Syntax:  Verification SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  3 [Proposed]
       Abstract Syntax:  Basic Grayscale Print Management Meta SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  5 [Proposed]
       Abstract Syntax:  Print Job SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  7 [Proposed]
       Abstract Syntax:  Printer SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  9 [Proposed]
       Abstract Syntax:  Basic Color Print Management Meta SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
[INFO] Received association request from AE: LINUX_DCP with IP: 192.168.20.11
[INFO] Accepted association request from LINUX_DCP
[INFO] LINUX_DCP -> Association accept:
Calling AE Title:       LINUX_DCP
Called AE Title:        DRYPIX
Remote host:            192.168.20.11
Remote port:            35954
Implementation Class:   Implementation Class UID [1.2.840.113619.6.81]
Implementation Version: fo-dicom 5.0.3
Maximum PDU Length:     16384
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  5
  Presentation Context:  1 [Accept]
       Abstract Syntax:  Verification SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  3 [Accept]
       Abstract Syntax:  Basic Grayscale Print Management Meta SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  5 [Accept]
       Abstract Syntax:  Print Job SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  7 [Accept]
       Abstract Syntax:  Printer SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  9 [Accept]
       Abstract Syntax:  Basic Color Print Management Meta SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
[INFO] LINUX_DCP <- N-Get request [0]
[INFO] N-Get request [0]
--------------------------------------------------------------------------------
 DIMSE Command:
--------------------------------------------------------------------------------
(0000,0000) UL 134                                              #     4, CommandGroupLength
(0000,0003) UI [1.2.840.10008.5.1.1.16]                         #    22, RequestedSOPClassUID
(0000,0100) US 272                                              #     2, CommandField
(0000,0110) US 0                                                #     2, MessageID
(0000,0800) US 257                                              #     2, CommandDataSetType
(0000,1001) UI [1.2.840.10008.5.1.1.17]                         #    22, RequestedSOPInstanceUID
(0000,1005) AT (0008,0070)/(0008,1090)/(2110,0010)/(2110,0020)/(#    36, AttributeIdentifierList

--------------------------------------------------------------------------------

[INFO] GetPrinter attribute (0008,0070) requested
GetPrinter attribute (0008,1090) requested
GetPrinter attribute (2110,0010) requested
GetPrinter attribute (2110,0020) requested
GetPrinter attribute (2110,0030) requested
GetPrinter attribute (0018,1000) requested
GetPrinter attribute (0018,1020) requested
GetPrinter attribute (0018,1200) requested
GetPrinter attribute (0018,1201) requested

[INFO] N-Get response [0]: Success
--------------------------------------------------------------------------------
 DIMSE Command:
--------------------------------------------------------------------------------
(0000,0002) UI [1.2.840.10008.5.1.1.16]                         #    22, AffectedSOPClassUID
(0000,0100) US 33040                                            #     2, CommandField
(0000,0120) US 0                                                #     2, MessageIDBeingRespondedTo
(0000,0800) US 514                                              #     2, CommandDataSetType
(0000,0900) US 0                                                #     2, Status
(0000,1000) UI [1.2.840.10008.5.1.1.17]                         #    22, AffectedSOPInstanceUID

--------------------------------------------------------------------------------
 DIMSE Dataset:
--------------------------------------------------------------------------------
(0008,0070) LO (no value available)                             #     0, Manufacturer
(0008,1090) LO (no value available)                             #     0, ManufacturerModelName
(0018,1000) LO (no value available)                             #     0, DeviceSerialNumber
(0018,1020) LO (no value available)                             #     0, SoftwareVersions
(0018,1200) DA [20220627]                                       #     8, DateOfLastCalibration
(0018,1201) TM [141730]                                         #     6, TimeOfLastCalibration
(2110,0010) CS [NORMAL]                                         #     6, PrinterStatus
(2110,0020) CS [NORMAL]                                         #     6, PrinterStatusInfo
(2110,0030) LO (no value available)                             #     0, PrinterName

--------------------------------------------------------------------------------

[INFO] LINUX_DCP -> N-Get response [0]: Success
[INFO] LINUX_DCP <- N-Create request [0]
[INFO] Create new film session 2.25.187161418386929995979298582379359099454
[INFO] LINUX_DCP -> N-Create response [0]: Success
[INFO] LINUX_DCP <- N-Create request [0]
[INFO] Applying display format STANDARD\1,1 for film box Local UID [2.25.245413958734309100720835175575326079203]
[INFO] Created new film box 2.25.245413958734309100720835175575326079203
[INFO] LINUX_DCP -> N-Create response [0]: Success
[INFO] LINUX_DCP <- N-Set request [0]
[INFO] Set image box 2.25.245413958734309100720835175575326079203.1
[INFO] LINUX_DCP -> N-Set response [0]: Success
[INFO] LINUX_DCP <- N-Action request [0]
                Action Type:    0001
[INFO] Creating new print job for film box 2.25.245413958734309100720835175575326079203
[INFO] Print Job 118397205278795094311105713460816335668 Status Pending: QUEUED
[INFO] LINUX_DCP -> N-EventReport request [1]
                Event Type:     0001
printJobDir.Create()
printJobDir.Create()
[INFO] LINUX_DCP <- N-EventReport response [1]: Success
                Event Type:     0001
[INFO] LINUX_DCP -> N-Action response [0]: Success
                Action Type:    0001
[INFO] LINUX_DCP <- N-Delete request [0]
[INFO] LINUX_DCP -> N-Delete response [0]: Success
[INFO] LINUX_DCP <- Association release request
[INFO] LINUX_DCP -> Association release response
[INFO] Print Job 118397205278795094311105713460816335668 Status Printing: QUEUED
[INFO] LINUX_DCP -> N-EventReport request [2]
                Event Type:     0002
[INFO] Socket error while reading PDU: ConnectionReset [10054]
[INFO] Socket error while writing PDU: ConnectionReset [10054]
[INFO] Connection closed
[ERROR] Exception creating PDV: FellowOakDicom.Network.DicomNetworkException: An IO exception occurred while sending a PDU

**Comment by XMAN274** [comment]
this error going to make me crazy
i tried every versions and any solution and don't know how to solve it
really make me sick

**Comment by HanaSongem** [comment]
I have a similar error when i try to echo a printer_SCP 
error log: 
`func: MoveNext Msg: case PRINT
[DEBUG] [IDLE] --> [CONNECTING]
[DEBUG] [CONNECTING] --> [REQUESTING ASSOCIATION]
[DEBUG] Sending association request from MYAE to PRINTSCP
[INFO] PRINTSCP -> Association request:
Calling AE Title:       MYAE
Called AE Title:        PRINTSCP
Remote host:            
Remote port:            0
Implementation Class:   Implementation Class UID [1.3.6.1.4.1.30071.8]
Implementation Version: fo-dicom 5.0.3
Maximum PDU Length:     262144
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  4
  Presentation Context:  1 [Proposed]
       Abstract Syntax:  Verification SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  3 [Proposed]
       Abstract Syntax:  Verification SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  5 [Proposed]
       Abstract Syntax:  Basic Grayscale Print Management Meta SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  7 [Proposed]
       Abstract Syntax:  Basic Color Print Management Meta SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
[INFO] PRINTSCP <- Association accept:
Calling AE Title:       MYAE
Called AE Title:        PRINTSCP
Remote host:            
Remote port:            0
Implementation Class:   Unknown [1.2.840.113564.3.3.2]
Implementation Version: DV685010v1.05
Maximum PDU Length:     131072
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  4
  Presentation Context:  1 [Accept]
       Abstract Syntax:  Verification SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  3 [Accept]
       Abstract Syntax:  Verification SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  5 [RejectUser]
       Abstract Syntax:  Basic Grayscale Print Management Meta SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  7 [RejectAbstractSyntaxNotSupported]
       Abstract Syntax:  Basic Color Print Management Meta SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
[DEBUG] Association request from MYAE to PRINTSCP has been accepted
[DEBUG] [REQUESTING ASSOCIATION] --> [SENDING REQUESTS]
[DEBUG] Queueing 1 requests
[DEBUG] C-Echo request [4] is being enqueued for sending
[INFO] PRINTSCP -> C-Echo request [4]
[INFO] PRINTSCP <- Abort: ServiceUser - NotSpecified
[INFO] Tried to close connection but queues are not empty, PDUs: 0, messages: 0, pending requests: 1
[DEBUG] Request [4]: Aborted
[DEBUG] C-Echo request [4]: Association was aborted
[ERROR] An error occurred while sending DICOM requests: FellowOakDicom.Network.DicomAssociationAbortedException: Association Abort [source: ServiceUser; reason: NotSpecified]
   at FellowOakDicom.Network.Client.Advanced.Association.AdvancedDicomClientAssociation.SendRequestAsync(DicomRequest dicomRequest, CancellationToken cancellationToken)+MoveNext()
   at FellowOakDicom.Network.Client.Advanced.Association.AdvancedDicomClientAssociation.SendRequestAsync(DicomRequest dicomRequest, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at FellowOakDicom.Network.Client.DicomClient.SendRequestAsync(IAdvancedDicomClientAssociation association, DicomRequest request, CancellationToken cancellationToken)
   at FellowOakDicom.Network.Client.DicomClient.SendRequestAsync(IAdvancedDicomClientAssociation association, DicomRequest request, CancellationToken cancellationToken)
   at FellowOakDicom.Network.Client.DicomClient.SendAsync(CancellationToken cancellationToken, DicomClientCancellationMode cancellationMode)
[DEBUG] [SENDING REQUESTS] --> [ABORTING ASSOCIATION]
[INFO] PRINTSCP -> Abort [source: ServiceUser; reason: NotSpecified]
[DEBUG] Waiting for association from MYAE to PRINTSCP @<no remote host>:0 to be released
[DEBUG] Association from MYAE to PRINTSCP @<no remote host>:0 has been aborted
[DEBUG] [ABORTING ASSOCIATION] --> [IDLE]
[INFO] Socket error while reading PDU: OperationAborted [995]
[INFO] Connection closed
line: 113, func: MoveNext Msg: Failed to check sopclassuid with ex:FellowOakDicom.Network.DicomAssociationAbortedException: Association Abort [source: ServiceUser; reason: NotSpecified]
   at FellowOakDicom.Network.Client.Advanced.Association.AdvancedDicomClientAssociation.SendRequestAsync(DicomRequest dicomRequest, CancellationToken cancellationToken)+MoveNext()
   at FellowOakDicom.Network.Client.Advanced.Association.AdvancedDicomClientAssociation.SendRequestAsync(DicomRequest dicomRequest, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at FellowOakDicom.Network.Client.DicomClient.SendRequestAsync(IAdvancedDicomClientAssociation association, DicomRequest request, CancellationToken cancellationToken)
   at FellowOakDicom.Network.Client.DicomClient.SendRequestAsync(IAdvancedDicomClientAssociation association, DicomRequest request, CancellationToken cancellationToken)
   at FellowOakDicom.Network.Client.DicomClient.SendAsync(CancellationToken cancellationToken, DicomClientCancellationMode cancellationMode)
   at FellowOakDicom.Network.Client.DicomClient.SendAsync(CancellationToken cancellationToken, DicomClientCancellationMode cancellationMode)`
